config/routes.rb
Rails.application.routes.draw do
 get 'tops/main'
 post 'tops/login'
 root 'tops#main'
 get 'tops/logout'
 get 'main/anketo'
 root 'main#anketo'
 resources :users, only:[:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todoufuken.rb
class Todoufuken < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 private
 def current_user
    if session[:uid]
        User.find_by(uid: session[:uid])
    end
 end
helper_method :current_user
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
    if session[:login_uid]
      render 'main'
    else
      render 'login'
    end
  end

  def login
    if User.find_by(uid:params[:uid], pass:params[:pass])
        session[:login_uid] = params[:uid]
        redirect_to tops_main_path
    else
        render 'error'
    end
  end
   def logout
       session.delete(:login_uid)
       redirect_to tops_main_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(uid: params[:user][:uid], pass: params[:user][:pass])
    if @user.save
      flash[:info] = 'ユーザを登録完了しました。'
      redirect_to users_path
    else
      render new_user_path
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Question</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/error.html.erb
<p>ログインに失敗しました！</p>

<%= link_to 'Back', tops_logout_path %>

app/views/tops/login.html.erb
<h2>ログイン画面</h2>
<% if flash[:notice] %>
  <p><font color="blue"><%= flash[:notice] %></font></p>
<% end %>  
<%= form_tag '/tops/login', method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <br>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag 'ログイン' %>
<% end %>  
<%= link_to "新規登録", new_user_path %>
<%= link_to "ユーザー情報", users_path %>

app/views/tops/main.html.erb
<h1>地方アンケートアプリ</h1>

<p>
ようこそ！
</p>
<%= link_to "ログアウト", tops_logout_path %>

<br>

<h2>募集中のアンケート</h2>

<p>
    1.ああああ<br>
    2.いいいい<br>
    3.うううう<br>
</p>

<%= link_to "アンケートを作成", new_anketo_path %><br>
<%= link_to "過去のアンケートを表示", anketo_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2>新規登録画面</h2>
<%= form_for @user, url: {action: :create} do |form| %>
 <%= label_tag :uid, 'ユーザーID' %>
 <%= text_field_tag :uid %>
 <br>
 <%= label_tag :pass, 'パスワード' %>
 <%= password_field_tag :pass %>
 <%= form.submit '登録'%>
<% end %>

<%= link_to 'Back', tops_main_path %>